### ISSUE TITLE
Wrong mention of Field33 in lockfile

### ISSUE THREAD

**Issue by hobofan** [field33/plow#23]
The `Plow.lock` currently contains "generated by Field33" in the auto-generated warning: https://github.com/field33/plow/blob/6e00303bac5d24c4276eb0b40be7d2f6917d91ef/plow_package_management/src/lock.rs#L59

It should reference Plow and not Field33.

My suggestion would be `generated by Field33` -> `generated by the Plow package manager`.

**Comment by alisomay** [comment]
When https://github.com/field33/plow/pull/24 is merged, this issue could be closed.
